### ISSUE TITLE
phpunit vs phpunit2 PEAR package?

### ISSUE THREAD

**Issue by patcon** [msonnabaum/chef-phpunit#1]
Hey Mark,

Just a first glimpse of this for me, but do you think the cookbook needs something to deal with PHPUnit vs PHPUnit2 (PHP4 vs PHP5)?

Cheers!

**Comment by msonnabaum** [comment]
Well, this installs phpunit 3.5 from the new channel. Is PHPUnit2 for php4? If so, I dont have an interest in supporting it.

Are you needing that?

**Comment by patcon** [comment]
Hmm.. sorry man. I'm too quick to post -- was looking at old channel.

PHP4: http://pear.php.net/package/PHPUnit
PHP5: http://pear.php.net/package/PHPUnit2

And for the record, I'll often post things to issue queues just to make note for myself and others, not because I expect the maintainer to fix it for me :)
