### ISSUE TITLE
php_pear definition doesn't seem to work

### ISSUE THREAD

**Issue by andrewhavens** [msonnabaum/chef-phpunit#3]
Hello,

I'm trying to use your phpunit recipe to install it on my Vagrant VM, but it doesn't seem to work for me. I'm not sure that it's your fault though. I downloaded a copy of the opscode php cookbook and a copy of your phpunit cookbook, and ran the recipes, but nothing happens. I see the lines in the console where it looks like it's installing the latest version of phpunit, and there are no errors in the console, but when I ssh into the VM, phpunit is not installed.

I tweaked your recipe to not use the php_pear definitions, and execute the commands manually, and it seemed to work. Here's my version:

```
execute "upgrade pear" do
  command "pear channel-update pear.php.net"
  command "pear upgrade-all"
  action :run
end

channels = %w{pear.phpunit.de components.ez.no pear.symfony-project.com}
channels.each do |chan|
  php_pear_channel chan do
    action [:discover, :update]
  end
end

php_pear "HTTP_Request2" do
  preferred_state "beta"
  action :install
end

php_pear "XML_RPC2" do
  action :install
end

execute "install phpunit" do
  command "pear -d preferred_state=beta install --alldeps pear.phpunit.de/PHPUnit"
  action :run
end
```

I don't know enough about chef to understand what's wrong with the original (or even how to properly write a chef recipe) so all I've done is hack something together that worked for me. Hopefully this helps you to figure out the problem.

**Comment by msonnabaum** [comment]
I ran into the same issue, and just pushed a fix. Please update and give it a shot.

In general though, if there's a bug in the pear LWRP, we need to fix it there. This time appeared to just be pear sucking.

**Comment by andrewhavens** [comment]
Thanks for fixing that. I'm curious, have you set up XDebug using Chef? I can't seem to get it to work with this PHPUnit install.

**Comment by andrewhavens** [comment]
I'm also curious...Why are you including the php recipe in your phpunit recipe? If I already have PHP installed, it's going to try and install it again.
