### ISSUE TITLE
Formatting error in metadata cause librarian resolver to fail

### ISSUE THREAD

**Issue by patcon** [msonnabaum/chef-phpunit#4]
https://github.com/msonnabaum/chef-phpunit/blob/master/metadata.rb#L7

```
depends "php::pear"
```

should be 

```
depends "php"
```

Will submit pull request

Also, I present to you: THE MANATEE.

![Manatee](http://i.imgur.com/Ixu5U.gif)

**Comment by msonnabaum** [comment]
Well done sir.
